server:
  port: 8888

# this config server connects to the git repository using the given url
spring:
  cloud:
    config:
      server:
        git:
          uri: C:/Users/AbuthairSheika/training/intellijdemos/microgitrepositories
#           uri: https://github.com/Abuthair/microgitrepository.git