server:
  port: 8761
  #Http://localhost:8761 is the url where the registry is running line no 18
  #this  is a rigistry so do not self register eureko to eureka line no 12
  #this is a rigistry so do not fectch the registry line no 11

  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        dafault-zone: http://${eureka.instance.hostname}:${server.port}
        fetch-registry: false
        register-with-eureka: false